# Generated by Django 4.1.4 on 2022-12-18 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="portfolio",
            name="title",
            field=models.CharField(max_length=100),
        ),
    ]
