# Generated by Django 4.1.4 on 2023-01-04 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_alter_portfolio_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="Newestimg",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=50, null=True)),
                ("photolink", models.CharField(blank=True, max_length=255, null=True)),
                ("create_date", models.DateField(auto_now_add=True, null=True)),
            ],
            options={"db_table": "newestimg",},
        ),
    ]
