# Generated by Django 4.1.4 on 2023-01-04 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("index", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="activity_end",
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name="activity",
            name="activity_starts",
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name="activity",
            name="create_date",
            field=models.DateField(auto_now=True),
        ),
    ]
