# Generated by Django 4.1.4 on 2023-01-04 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("index", "0002_activity_activity_end_activity_activity_starts_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="activity_end",
            field=models.CharField(default=0, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name="activity",
            name="activity_starts",
            field=models.CharField(default=0, max_length=8),
        ),
    ]
