# Generated by Django 4.1.4 on 2023-01-05 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="ptype",
            field=models.CharField(default=0, max_length=20),
        ),
    ]
